services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Models/ErrorViewModel.cs
namespace Ntigra.Ecommerce.Platform.Web.Models
{
    public class ErrorViewModel
    {
        public string? ErrorCode { get; set; }
        public string? ErrorMessage { get; set; }
    }
}

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Ntigra.Ecommerce.Platform.Application.Contract.Cart;
using Ntigra.Ecommerce.Platform.Web.Models;

namespace Ntigra.Ecommerce.Platform.Web.Controllers;
public sealed class CartController(ICartService cartService) : Controller
{
    public async Task<IActionResult> Add(int productId)
    {
        var response = await cartService.AddToCartAsync(productId);
        var count = await cartService.GetCartItemCountAsync();
        return Json(new
        {
            success = response.Status,
            count,
            errorCode = response.Status ? null : response.ResponseCode,
            errorMessage = response.Status ? null : response.ResponseMessage
        });
    }

    public async Task<IActionResult> Remove(int productId)
    {
        var response = await cartService.RemoveFromCartAsync(productId);
        var count = await cartService.GetCartItemCountAsync();
        return Json(new
        {
            success = response.Status,
            count,
            errorCode = response.Status ? null : response.ResponseCode,
            errorMessage = response.Status ? null : response.ResponseMessage
        });
    }

    public async Task<IActionResult> Index()
    {
        var response = await cartService.GetCartSummaryAsync();
        return response.Status ? View(response.Data) : View("Error", new ErrorViewModel
        {
            ErrorCode = response.ResponseCode,
            ErrorMessage = response.ResponseMessage
        });
    }

}

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Ntigra.Ecommerce.Platform.Application.Contract.Product;
using Ntigra.Ecommerce.Platform.Web.Models;

namespace Ntigra.Ecommerce.Platform.Web.Controllers
{
    public sealed class ProductController(IProductService productService) : Controller
    {
        public async Task<IActionResult> Index()
        {
            var response = await productService.GetAllProductsAsync();
            return response.Status ? 
                View(response.Data) : View("Error", new ErrorViewModel
                {
                    ErrorCode = response.ResponseCode,
                    ErrorMessage = response.ResponseMessage
                });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel
            {
                ErrorCode = "500",
                ErrorMessage = "Unexcpected error"
            });
            
        }
    }
}

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/ViewComponents/CartCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Ntigra.Ecommerce.Platform.Application.Contract.Cart;
namespace Ntigra.Ecommerce.Platform.Web.ViewComponents;
public class CartCountViewComponent(ICartService cartService) : ViewComponent
{ 
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var count = await cartService.GetCartItemCountAsync();
        return View(count);
    }
}

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Cart/Index.cshtml
@model Ntigra.Ecommerce.Platform.Application.Contract.Cart.CartSummaryResponseDto
@{
    ViewBag.Title = "Cart Summary";
    ViewBag.SubTitle = "Cart";
}
@section styles
{

}

@await Html.PartialAsync("~/Views/Shared/Partials/_PageTitle.cshtml")

<div class="row">
    <div class="col-12">
        <div class="card" data-table="" data-table-rows-per-page="8">
            <div class="card-header border-light justify-content-between">
                <div class="d-flex gap-2">
                    <div class="app-search">
                        <input class="form-control" data-table-search="" placeholder="Search product name..."
                               type="search" />
                        <i class="app-search-icon text-muted" data-lucide="search"></i>
                    </div> 
                </div>  
            </div>  
            <div class="table-responsive">
                <table class="table table-custom table-centered table-select table-hover w-100 mb-0">
                    <thead class="bg-light align-middle bg-opacity-25 thead-sm">
                        <tr class="text-uppercase fs-xxs">
                            <th>Product Name</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th>Discount %</th> 
                            <th>Quantity</th>
                            <th>Final Price</th>
                            <th class="text-center" style="width: 1%;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>
                                    <div class="d-flex">
                                            <h5 class="mb-0">@item.ProductName</h5>
                                    </div>
                                </td>
                                <td>@item.Description</td>
                                <td>₹@item.OriginalPrice</td>
                                <td>
                                    @if (Model.HasDiscount)
                                    {
                                        <span class="text-success">
                                            -₹@item.DiscountAmount (@item.DiscountPercent%)
                                        </span>
                                    }
                                    else
                                    {
                                        <span>-</span>
                                    }
                                </td>
                                
                                <td>@item.Quantity</td>
                                <td>₹@item.FinalPrice</td> 
                                <td>
                                    <div class="d-flex justify-content-center gap-1"> 
                                        <a class="btn btn-danger btn-icon btn-sm rounded-circle remove-from-cart" data-id="@item.ProductId">
                                            <i class="ti ti-trash fs-lg"></i>
                                        </a>

                                    </div>

                                </td>

                            </tr>
                        } 
                    </tbody>
                </table>
            </div>
            <div class="card-footer border-0">
                <div class="d-flex justify-content-between align-items-center">
                    <div data-table-pagination-info="products"></div>
                    <div data-table-pagination=""></div>
                </div>
            </div>
        </div>
    </div><!-- end col -->
</div><!-- end row -->
<hr />

<div class="text-end">
    <p><strong>Total Amount:</strong> ₹@Model.TotalPrice</p>
    <p><strong>Total Discount:</strong> ₹@Model.TotalDiscount</p>

    <h4 class="text-success">
        Final Payable Amount: ₹@Model.FinalPrice
    </h4>
</div>
@section scripts
{
    <script src="/js/custom-table.js"></script>
}

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Products";
    ViewBag.Subtitle = "Product";
}
@section styles
{

}

@await Html.PartialAsync("~/Views/Shared/Partials/_PageTitle.cshtml")

<div class="row">
    <div class="col-12">
        <div class="card" data-table="" data-table-rows-per-page="8">
            <div class="card-header border-light justify-content-between">
                <div class="d-flex gap-2">
                    <div class="app-search">
                        <input class="form-control" data-table-search="" placeholder="Search product name..."
                               type="search" />
                        <i class="app-search-icon text-muted" data-lucide="search"></i>
                    </div> 
                </div>  
            </div>
            <div class="table-responsive">
                <table class="table table-custom table-centered table-select table-hover w-100 mb-0">
                    <thead class="bg-light align-middle bg-opacity-25 thead-sm">
                        <tr class="text-uppercase fs-xxs">
                            <th>Product Name</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th>Discount %</th>
                            <th class="text-center" style="width: 1%;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model)
                        {
                            <tr>
                                <td>
                                    <div class="d-flex">
                                            <h5 class="mb-0">@product.Name</h5>
                                    </div>
                                </td>
                                <td>@product.Description</td>
                                <td>₹@product.Price</td>
                                <td>@product.DiscountPercent</td>
                                <td>
                                    <div class="d-flex justify-content-center gap-1">
                                        <a class="btn btn-default btn-icon btn-sm rounded-circle add-to-cart"
                                           data-id="@product.Id">
                                            <i class="fs-3" data-lucide="package-plus"></i>
                                        </a>
                                    </div> 
                                </td>
                            </tr>
                        } 
                    </tbody>
                </table>
            </div>
            <div class="card-footer border-0">
                <div class="d-flex justify-content-between align-items-center">
                    <div data-table-pagination-info="products"></div>
                    <div data-table-pagination=""></div>
                </div>
            </div>
        </div>
    </div><!-- end col -->
</div><!-- end row -->
@section scripts
{
    <script src="/js/custom-table.js"></script>
}

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Shared/Components/CartCount/Default.cshtml
@model int

<a asp-controller="Cart"
   asp-action="Index"
   class="topbar-link position-relative">

    <i class="fs-xxl" data-lucide="shopping-cart"></i>

    @if (Model > 0)
    {
        <span class="badge text-bg-danger badge-circle topbar-badge">
            @Model
        </span>
    }
</a> 

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Shared/Partials/_Footer.cshtml
<!-- Footer Start -->
<footer class="footer bg-black text-light">
    <div class="container">
        <div class="row gy-4 align-items-center">
            <!-- Logo & Contact -->
            <div class="col-md-6 text-center text-md-start">
                <img src="/images/logo.png" alt="Ntigra Logo" class="mb-3 ms-5" style="max-width: 100px;">
                <ul class="list-unstyled mb-0  text-white">
                    <li class="mb-1"><i data-lucide="phone" class="me-2"></i></i>+971 (04) 665 8849</li>
                    <li class="mb-1"><i data-lucide="mail" class="me-2  "></i></i>WeBusiness@ntigra.com</li>
                    <li class="mb-1"><i data-lucide="map-pin" class="me-2  "></i></i>Business Bay, Dubai - UAE</li>
                </ul>
            </div>

            <!-- Social Links -->
            <div class="col-md-6 text-center text-md-end">
                <h6 class="mb-3">Follow Us</h6>
                <a href="#" class="btn btn-default btn-icon btn-sm rounded-circle me-2" aria-label="LinkedIn">
                    <i data-lucide="linkedin"></i>
                </a>
                <a href="#" class="btn btn-default btn-icon btn-sm rounded-circle me-2" aria-label="Facebook">
                    <i data-lucide="facebook"></i>
                </a>
                <a href="#" class="btn btn-default btn-icon btn-sm rounded-circle" aria-label="Twitter">
                    <i data-lucide="twitter"></i>
                </a>
            </div>
        </div>

        <!-- Copyright -->
        <div class="row">
            <div class="col text-center text-secondary small">
                &copy; <script>document.write(new Date().getFullYear())</script> Ntigra by
                <span class="fw-semibold text-white">Sahir Abdulla</span>
            </div>
        </div>
    </div>
</footer>
<!-- Footer End -->
 

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Shared/Partials/_FooterScripts.cshtml
<!-- Vendor js -->
<script src="/js/vendors.min.js"></script>
<!-- App js -->
<script src="/js/app.js"></script>

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Shared/Partials/_HeadCss.cshtml
<!-- Theme Config Js -->
<script src="/js/config.js"></script>
<!-- Vendor css -->
<link href="/css/vendors.min.css" rel="stylesheet" type="text/css"/>
<!-- App css -->
<link href="/css/app.min.css" rel="stylesheet" type="text/css"/>

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Shared/Partials/_PageTitle.cshtml
@{
    var title = ViewBag.Title;
    var subtitle = ViewBag.SubTitle;
}

@if (!string.IsNullOrEmpty(title))
{
<div class="page-title-head d-flex align-items-center">
  <div class="flex-grow-1">
    <h4 class="fs-xl fw-bold m-0">@title</h4>
  </div>
  @if (string.Equals(subtitle, "Cart", StringComparison.OrdinalIgnoreCase))
        {
            <div class="d-flex gap-1"> 
                <a class="btn btn-primary ms-1" href="/">
                    <i class="fs-sm me-2" data-lucide="plus"></i> Add Product
                </a>
            </div>
        }
        @if (string.Equals(subtitle, "Product", StringComparison.OrdinalIgnoreCase))
        {
            <div class="d-flex gap-1">
                <a class="btn btn-primary ms-1" href="/Cart">
                    <i class="fs-sm me-2" data-lucide="shopping-cart"></i> Go to Cart
                </a>
            </div>
        }
</div>
}

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Shared/Partials/_TitleMeta.cshtml
<meta charset="utf-8"/>
@{
    var title = ViewBag.Title != null
        ? ViewBag.Title
        : "Ntigra";
}

<title>@title</title>
<meta content="width=device-width, initial-scale=1" name="viewport"/> 
<!-- App favicon -->
<link href="~/images/favicon.ico" rel="shortcut icon"/>

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Shared/Partials/_Topbar.cshtml
<!-- Topbar Start -->
<header class="app-topbar">
    <div class="container-fluid topbar-menu">
        <div class="d-flex align-items-center gap-2">
            <!-- Topbar Brand Logo -->
            <div class="logo-topbar">
                <!-- Logo light -->
                <a class="logo-light" href="#">
                    <span class="logo-lg">
                        <img alt="logo" src="/images/logo.png" />
                        </span>
                    <span class="logo-sm">
                        <img alt="small logo" src="/images/logo.png" />
                        </span>
                </a>
                <!-- Logo Dark -->
                <a class="logo-dark" href="#">
                    <span class="logo-lg">
                        <img alt="dark logo" src="/images/logo.png" />
                        </span>
                    <span class="logo-sm">
                        <img alt="small logo" src="/images/logo.png" />
                        </span>
                </a>
            </div>
            <!-- Sidebar Menu Toggle Button -->
            <button class="sidenav-toggle-button btn btn-default btn-icon">
                <i class="ti ti-menu-4 fs-22"></i>
            </button>
            <!-- Horizontal Menu Toggle Button -->
            <button class="topnav-toggle-button px-2" data-bs-target="#topnav-menu-content" data-bs-toggle="collapse">
                <i class="ti ti-menu-4 fs-22"></i>
            </button>
        </div> <!-- .d-flex-->
        <div class="d-flex align-items-center gap-2">
            <!-- Search -->
            <div class="app-search d-none d-xl-flex me-2">
                <input class="form-control topbar-search rounded-pill" name="search" placeholder="Quick Search..."
                       type="search"/>
                <i class="app-search-icon text-muted" data-lucide="search"></i>
            </div>
            <!-- Dropdown -->
            <div class="topbar-item">
                @await Component.InvokeAsync("CartCount")
            </div>

        </div>
    </div>
</header>
<!-- Topbar End -->

services/ecommerce/src/Ntigra.Ecommerce.Platform.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

@{
    var html_attributes = ViewBag.HTMLAttributes != null ? ViewBag.HTMLAttributes : "";
    var html_class = ViewBag.HTMLClass != null ? ViewBag.HTMLClass : "";
}

<html lang="en" data-layout="topnav" @html_attributes class="@html_class">

<head>
    @await Html.PartialAsync("~/Views/Shared/Partials/_TitleMeta.cshtml")
    @RenderSection("styles", false)
    @await Html.PartialAsync("~/Views/Shared/Partials/_HeadCSS.cshtml")
</head>

<body>

    <div class="wrapper">

        @await Html.PartialAsync("~/Views/Shared/Partials/_Topbar.cshtml") 

        <div class="content-page">

            <div class="container-fluid">

                @RenderBody()

            </div>

            @await Html.PartialAsync("~/Views/Shared/Partials/_Footer.cshtml")
        </div>

    </div>
    <div id="confirm-modal" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Confirmation</h4>
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p id="confirm-modal-message" class="mb-0"></p>
            </div>
            <div class="modal-footer">
                <button type="button"
                        class="btn btn-primary"
                        data-bs-dismiss="modal">
                    Okay
                </button>
            </div>
        </div>
    </div>
</div>

<div id="error-modal" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0">
            <div class="modal-header bg-danger text-white">
                <h5 class="modal-title d-flex align-items-center gap-2">
                    <i data-lucide="alert-circle"></i>
                    Error
                </h5>
                <button type="button"
                        class="btn-close btn-close-white"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <p id="error-modal-message" class="mb-1 fw-semibold"></p>
                <small id="error-modal-code" class="text-muted"></small>
            </div>

            <div class="modal-footer">
                <button type="button"
                        class="btn btn-danger"
                        data-bs-dismiss="modal">
                    Okay
                </button>
            </div>
        </div>
    </div>
</div>


    @await Html.PartialAsync("~/Views/Shared/Partials/_FooterScripts.cshtml")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>